//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.Database2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Drumble.DomainDrivenArchitecture.Domain.EntityFramework;
    
    public partial class DDArchTest2Entities : EntityFrameworkContext
    {
        public DDArchTest2Entities()
            : base("name=DDArchTest2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<StopEntity> StopEntities { get; set; }
        public virtual DbSet<StopHubEntity> StopHubEntities { get; set; }
    }
}
