//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.Database2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StopHubEntity
    {
        public System.Guid Id { get; set; }
        public string HubName { get; set; }
        public System.Guid StopId { get; set; }
    
        public virtual StopEntity Stop { get; set; }
    }
}
