//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestConsole.Database2
{
    using System.Linq;
    using System;
    using System.Collections.Generic;
    
    public partial class StopEntity
    {
        public StopEntity()
        {
            this.StopHubs = new HashSet<StopHubEntity>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<StopHubEntity> StopHubs { get; set; }

        public static StopEntity CreateFrom(Stop stop)
        {
            var stopEntity = new StopEntity();

            stopEntity.Id = stop.Id;
            stopEntity.Name = stop.Name;
            stopEntity.StopHubs = stop.Hubs.Select(x => new StopHubEntity() { Id = Guid.NewGuid(), HubName = x }).ToList();

            return stopEntity;
        }

        public void UpdateFrom(Stop stop)
        {
            Id = stop.Id;
            Name = stop.Name;
            StopHubs = stop.Hubs.Select(x => new StopHubEntity() { Id = Guid.NewGuid(), HubName = x }).ToList();
        }

        public Stop HydrateTo()
        {
            return new Stop(Id) { Name = Name, Hubs = StopHubs.Select(x => x.HubName).ToList() };
        }
    }
}
